baseURL = "https://demo.gethugothemes.com/restaurant/examplesite/"
languageCode = "en-us"
paginate = 4
summaryLength = "10"
theme = "restaurant-hugo"
title = "Restaurant Hugo"
[[menu.main]]
URL = "contact-us"
name = "Entre em contato"
weight = 6
[[menu.main]]
URL = "subscribe"
name = "Novidades"
weight = 5
[[menu.main]]
URL = "price"
name = "Serviços"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "about-us"
name = "Sobre o Du Chef"
weight = 2
[[menu.main]]
URL = "hero-area"
name = "Home"
weight = 1
[params]
author = "Themefisher"
copyright = "Copyright &copy; 2021 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
description = "This is meta description"
google_analitycs_id = "Your ID"
logo = "images/logo.png"
main_sections = ["post"]
[params.footer]
blogTitle = "LATEST <span>BLOG POSTS</span>"
contactInfoTitle = "CONTACT <span>INFO</span> "
enable = true
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"
[[params.footer.contactItem]]
content = "016742 323313"
icon = "fa fa-phone"
title = "Telephone"
[[params.footer.contactItem]]
content = "2046 Blue Spruce Lane Laurel Canada"
icon = "fa fa-map-marker"
title = "Address"
[[params.footer.contactItem]]
content = "rest@gmail.com - rest@mail.ru"
icon = "fa fa-envelope"
title = "E mail"
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"
[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"
[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"
[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"
[params.preloader]
enable = false
preloader = ""
